### ISSUE TITLE
The Image Release Form requires permission to access

### ISSUE THREAD

**Issue by camilaavilarinho** [DemocracyEarth/ambassadors#1]
I tried to open it and got the message that the form "can only be viewed by users in the owner's organization".

**Comment by SFSandra** [comment]
Thanks Camila - I've assigned to @paulamlb who can generate a public link to replace the existing link, so that everyone with the link can access the form.Thanks for helping us fix this!

**Comment by paulamlb** [comment]
Thanks for pointing this to us! The form should be accessible now :) Could you please test it an confirm that you can access it @camilaavilarinho ?

**Comment by camilaavilarinho** [comment]
@paulamlb yes, it's accessible now, thanks!
