### ISSUE TITLE
Ambassadors channel link

### ISSUE THREAD

**Issue by camilaavilarinho** [DemocracyEarth/ambassadors#2]
The ambassadors channel link is redirecting to the developers channel.

**Comment by SFSandra** [comment]
Hi Camila - can you point me to the link? Thanks for spotting and sharing....

**Comment by camilaavilarinho** [comment]
It's Here: 
<img width="953" alt="screen shot 2017-12-17 at 11 01 11" src="https://user-images.githubusercontent.com/11904362/34078841-b1eaffe6-e319-11e7-80e6-4ca37118b5ee.png">

I also noticed that there's no #ambassadors channel on Slack
Can I create one and send a PR to fix the link?

**Comment by paulamlb** [comment]
That sounds great @camilaavilarinho :) The only thing is we actually have an ambassadors channel but it was private. So we will change it's name and then create a new, public one (and ask the members to switch). As soon as it's done I'll let you know!

**Comment by paulamlb** [comment]
Done! Could you please test the links one more time and confirm that you can access the channel now?
Thanks :)

**Comment by camilaavilarinho** [comment]
@paulamlb the link is ok now, thanks!
