### ISSUE TITLE
Can't add event in Basecamp

### ISSUE THREAD

**Issue by Policynotic** [DemocracyEarth/ambassadors#5]
The option is missing under "schedule" for "Add An Event". Am I missing permissions?

**Comment by paulamlb** [comment]
I don't think so.. Neither the green button on the upper left corner or the one below the schedule appear?

<img width="821" alt="screen shot 2018-05-29 at 10 29 54" src="https://user-images.githubusercontent.com/18194034/40661926-4af95f8e-632b-11e8-9296-9c4228778cc4.png">
